# Template from:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install nox>=2022.8.7
  - apt-get install -y
  # Add the dummy pdflatex to the PATH
  - cp ./tests/dummy_pdflatex.sh /usr/local/bin/pdflatex
  - chmod a+x /usr/local/bin/pdflatex

lint_and_test_py38:
  image: python:3.8
  script:
    - nox -p "3.8"

lint_and_test_py310:
  image: python:3.10
  script:
    - nox -p "3.10"

lint_and_test_py312:
  image: python:3.12
  script:
    - nox -p "3.12"
